kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io