kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-attacher-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-attacher-role
  apiGroup: rbac.authorization.k8s.io
