= Parameters

The parent key for all of the following parameters is `csi_cloudscale`.

== `namespace`

[horizontal]
type:: string
default:: `syn-csi-cloudscale`

The namespace in which to install the driver.
Unless `kube-system` is chosen, the component will take ownership of the namespace.
In K8s prior to 1.17, the driver won't run in namespaces other than `kube-system`.
This is because the priority class `system-cluster-critical` is only available to pods in namespace `kube-system`.
See https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default[the Kubernetes priority class consumption] documentation for instructions on how to allow the driver to run in a namespace other than `kube-system`.

== `version`

[horizontal]
type:: string
default:: `v3.2.0`

Version of the driver to install.
See https://github.com/cloudscale-ch/csi-cloudscale/releases[available versions].
See https://github.com/cloudscale-ch/csi-cloudscale#kubernetes-compatibility[Kubernetes compatibility] to choose the right version for your cluster.


== `enabled`

[horizontal]
type:: boolean
default:: `true`

Switch to enable or disable the component. See https://github.com/projectsyn/commodore/issues/71[this issue] for further details.


== `api_token`

[horizontal]
type:: string
default:: Vault reference

Cloudscale API token to be used by the CSI driver.
This should be a reference to a secret in Vault instead of the plaintext token.


== `fs_type`

[horizontal]
type:: string
default:: ext4

The filesystem type used in the storage classes.

== `driver_daemonset_tolerations`

[horizontal]
type:: dictionary
default:: `{}`

Tolerations that should be applied to the CSI node driver daemonset.
The component will transform entries in the dictionary to valid Kubernetes `tolerations` entries.
The component will reuse the key in the dictionary as value for field `key` in the `tolerations` entry.

=== Example

Allow the CSI node driver daemonset to be scheduled on nodes which have a `storagenode` taint.

.cluster-id.yaml
[source,yaml]
----
parameters:
  csi_cloudscale:
    driver_daemonset_tolerations:
      storagenode:
        operator: Exists
----

.Resulting configuration in the node driver DaemonSet
[source,yaml]
----
# ... remaining object omitted ...
spec:
  template:
    spec:
      # ... remaining spec omitted ...
      tolerations:
        - key: storagenode
          operator: Exists
----

== `resources`

[horizontal]
type:: dict
default:: https://github.com/projectsyn/component-csi-cloudscale/blob/master/class/defaults.yml[See `class/defaults.yml`]

Resource requests and limits to apply to individual CSI driver containers.

The component looks for keys matching the individual container names for the controller StatefulSet and CSI driver daemonset in the keys `controller` and `csi_driver` of this parameter respectively.

The value of such a key -- if found -- is used as the container's `resources` field.

The component supports removing requests or limits by setting the corresponding fields to `null`.

[NOTE]
====
The component doesn't validate provided requests and limits.
It's the user's responsibility to provide values which result in a valid container spec.
====

=== Example

This example increases the memory limit for the `csi-cloudscale-plugin` container for both the controller and the csi_driver to `256Mi`.

[source,yaml]
----
parameters:
  csi_cloudscale:
    resources:
      controller:
        csi-cloudscale-plugin:
          limits:
            memory: 256Mi
      csi_driver:
        csi-cloudscale-plugin:
          limits:
            memory: 256Mi
----
