name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - docs-vale
    steps:
      - uses: actions/checkout@v2
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
